export const themes = {
    dark: {
        name: 'Dark',
        background: '#000000',
        display: '#000000',
        button: '#333333',
        operator: '#ff9f0a',
        function: '#a5a5a5',
        text: '#ffffff',
        secondaryText: '#999999',
    },
    light: {
        name: 'Light',
        background: '#f1f2f3',
        display: '#ffffff',
        button: '#ffffff',
        operator: '#ff9f0a',
        function: '#d2d3db',
        text: '#333333', // Daha koyu
        secondaryText: '#555555', // Daha koyu
    },
    neonPink: {
        name: 'Neon Pink',
        background: '#1a1a1a',
        display: '#1a1a1a',
        button: '#2d2d2d',
        operator: '#ff1493',
        function: '#ff69b4',
        text: '#ffffff',
        secondaryText: '#ff69b4',
    },
    oceanBreeze: {
        name: 'Ocean Breeze',
        background: '#1a374d',
        display: '#1a374d',
        button: '#406882',
        operator: '#6998ab',
        function: '#b1d0e0',
        text: '#ffffff',
        secondaryText: '#b1d0e0',
    },
    forest: {
        name: 'Forest',
        background: '#1b4332',
        display: '#1b4332',
        button: '#2d6a4f',
        operator: '#40916c',
        function: '#74c69d',
        text: '#ffffff',
        secondaryText: '#95d5b2',
    },
    sunset: {
        name: 'Sunset',
        background: '#33415c',
        display: '#33415c',
        button: '#5c677d',
        operator: '#f7a072',
        function: '#ed6a5a',
        text: '#ffffff',
        secondaryText: '#f7a072',
    },
    lavender: {
        name: 'Lavender',
        background: '#4a4e69',
        display: '#4a4e69',
        button: '#686d8c',
        operator: '#9a8c98',
        function: '#c9ada7',
        text: '#ffffff',
        secondaryText: '#f2e9e4',
    },
    mint: {
        name: 'Mint',
        background: '#2c6e49',
        display: '#2c6e49',
        button: '#4c956c',
        operator: '#fefee3',
        function: '#d8f3dc',
        text: '#ffffff',
        secondaryText: '#b7e4c7', // Daha uyumlu
    },
    coral: {
        name: 'Coral',
        background: '#ff4d6d',
        display: '#ff4d6d',
        button: '#ff758f',
        operator: '#590d22',
        function: '#590d22',
        text: '#ffffff',
        secondaryText: '#ffe4e1', // Daha açık
    },
    galaxy: {
        name: 'Galaxy',
        background: '#0d1b2a',
        display: '#0d1b2a',
        button: '#1b263b',
        operator: '#e0fbfc',
        function: '#98c1d9',
        text: '#ffffff',
        secondaryText: '#3d5a80',
    },
    coffee: {
        name: 'Coffee',
        background: '#463f3a',
        display: '#463f3a',
        button: '#8a817c',
        operator: '#bcb8b1',
        function: '#f4f3ee',
        text: '#ffffff',
        secondaryText: '#d5cab0',
    },
    retro: {
        name: 'Retro',
        background: '#2b2d42',
        display: '#2b2d42',
        button: '#8d99ae',
        operator: '#ef233c',
        function: '#d90429',
        text: '#ffffff',
        secondaryText: '#edf2f4',
    },
    cyberpunk: {
        name: 'Cyberpunk',
        background: '#2d00f7',
        display: '#2d00f7',
        button: '#6a00f4',
        operator: '#ff0a54',
        function: '#8900f2',
        text: '#ffffff',
        secondaryText: '#a100f2',
    },
    pastel: {
        name: 'Pastel',
        background: '#ffd6ff',
        display: '#ffd6ff',
        button: '#e7c6ff',
        operator: '#6247aa',
        function: '#6247aa',
        text: '#333333', // Daha koyu
        secondaryText: '#6247aa',
    },
    neonGreen: {
        name: 'Neon Green',
        background: '#1a1a1a',
        display: '#1a1a1a',
        button: '#2d2d2d',
        operator: '#39ff14',
        function: '#32cd32',
        text: '#ffffff',
        secondaryText: '#39ff14',
    },
    autumn: {
        name: 'Autumn',
        background: '#582f0e',
        display: '#582f0e',
        button: '#7f4f24',
        operator: '#936639',
        function: '#a68a64',
        text: '#ffffff',
        secondaryText: '#b6ad90',
    },
    arctic: {
        name: 'Arctic',
        background: '#457b9d',
        display: '#457b9d',
        button: '#a8dadc',
        operator: '#f1faee',
        function: '#e63946',
        text: '#ffffff',
        secondaryText: '#1d3557',
    },
    candy: {
        name: 'Candy',
        background: '#ff99c8',
        display: '#ff99c8',
        button: '#fcf6bd',
        operator: '#4a0259',
        function: '#4a0259',
        text: '#1a1a1a',
        secondaryText: '#4a0259',
    },
    midnight: {
        name: 'Midnight',
        background: '#03071e',
        display: '#03071e',
        button: '#370617',
        operator: '#6a040f',
        function: '#9d0208',
        text: '#ffffff',
        secondaryText: '#dc2f02',
    },
    synthwave: {
        name: 'Synthwave',
        background: '#2b1055',
        display: '#2b1055',
        button: '#7597de',
        operator: '#ff2a6d',
        function: '#d61c4e',
        text: '#ffffff',
        secondaryText: '#05d9e8',
    },
};
